name: Heroku Staging Deployment
on:
  push:
    branches: [ master ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Staging to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.EMAIL}}
          heroku_app_name: ${{secrets.STAGING_HEROKU_APP_NAME}}
